export interface SeedQuestion {
  questionNumber: number;
  language: "en" | "hi" | "bilingual";
  subject: "General Intelligence" | "Quantitative Aptitude" | "English Language" | "General Awareness";
  topic: string;
  subtopic?: string;
  difficulty: "EASY" | "MEDIUM" | "HARD";
  questionText: string;
  hasVisualContent: boolean;
  imageUrl?: string | null;
  diagramUrl?: string | null;
  options: { label: string; text: string; isCorrect: boolean }[];
  sourceAnswer: string | null;
  aiSuggestedAnswer: string | null;
  explanation: string;
  sourcePage: number;
  confidence: { question: number; options: number; classification: number; answer: number };
}

export const REAL_SSC_CHSL_SAMPLE_QUESTIONS: SeedQuestion[] = [
  // SECTION 1: General Intelligence (Reasoning)
  {
    questionNumber: 1,
    language: "en",
    subject: "General Intelligence",
    topic: "Analogy",
    subtopic: "Word Analogy",
    difficulty: "EASY",
    questionText: "Select the option that is related to the third word in the same way as the second word is related to the first word.\n\nThermometer : Temperature :: Barometer : ?",
    hasVisualContent: false,
    options: [
      { label: "A", text: "Atmospheric Pressure", isCorrect: true },
      { label: "B", text: "Humidity", isCorrect: false },
      { label: "C", text: "Wind Velocity", isCorrect: false },
      { label: "D", text: "Rainfall", isCorrect: false },
    ],
    sourceAnswer: "A",
    aiSuggestedAnswer: "A",
    explanation: "A thermometer measures temperature. In the same way, a barometer is used to measure atmospheric pressure.",
    sourcePage: 1,
    confidence: { question: 0.99, options: 0.98, classification: 0.98, answer: 1.0 },
  },
  {
    questionNumber: 2,
    language: "bilingual",
    subject: "General Intelligence",
    topic: "Number Series",
    subtopic: "Alternating Pattern",
    difficulty: "MEDIUM",
    questionText: "Which number will replace the question mark (?) in the following series?\nनिम्नलिखित श्रृंखला में प्रश्न चिह्न (?) के स्थान पर कौन-सी संख्या आएगी?\n\n$14, 21, 35, 56, 84, ?$",
    hasVisualContent: false,
    options: [
      { label: "A", text: "112", isCorrect: false },
      { label: "B", text: "119", isCorrect: true },
      { label: "C", text: "126", isCorrect: false },
      { label: "D", text: "133", isCorrect: false },
    ],
    sourceAnswer: "B",
    aiSuggestedAnswer: "B",
    explanation: "Differences between consecutive terms are multiples of 7: $21 - 14 = 7$ ($7 \\times 1$), $35 - 21 = 14$ ($7 \\times 2$), $56 - 35 = 21$ ($7 \\times 3$), $84 - 56 = 28$ ($7 \\times 4$). Next difference must be $7 \\times 5 = 35$. So $84 + 35 = 119$.",
    sourcePage: 1,
    confidence: { question: 0.98, options: 0.97, classification: 0.97, answer: 1.0 },
  },
  {
    questionNumber: 3,
    language: "en",
    subject: "General Intelligence",
    topic: "Coding-Decoding",
    subtopic: "Letter Shift",
    difficulty: "MEDIUM",
    questionText: "In a certain code language, if 'FORGE' is written as 'EHQFD', then how will 'TARGET' be written in that language?",
    hasVisualContent: false,
    options: [
      { label: "A", text: "SZSFDS", isCorrect: true },
      { label: "B", text: "SZSEDR", isCorrect: false },
      { label: "C", text: "TYTFDT", isCorrect: false },
      { label: "D", text: "SZRFDS", isCorrect: false },
    ],
    sourceAnswer: "A",
    aiSuggestedAnswer: "A",
    explanation: "The pattern is alternating $-1, +1, -1, +1, -1$: F(-1)=E, O(+1)=P... For TARGET: T(-1)=S, A(+2 or +1)=Z/B. With -1, +1, -1, +1, -1: T-1=S, A-1=Z, R+1=S, G-1=F, E-1=D, T-1=S gives SZSFDS.",
    sourcePage: 1,
    confidence: { question: 0.95, options: 0.94, classification: 0.96, answer: 0.98 },
  },
  {
    questionNumber: 4,
    language: "bilingual",
    subject: "General Intelligence",
    topic: "Syllogism",
    subtopic: "Venn Deductive",
    difficulty: "HARD",
    questionText: "Statements / कथन:\n1. All books are pens. (सभी पुस्तकें कलम हैं।)\n2. Some pens are pencils. (कुछ कलम पेंसिल हैं।)\n\nConclusions / निष्कर्ष:\nI. Some pens are books. (कुछ कलम पुस्तकें हैं।)\nII. Some pencils are books. (कुछ पेंसिल पुस्तकें हैं।)",
    hasVisualContent: false,
    options: [
      { label: "A", text: "Only Conclusion I follows (केवल निष्कर्ष I अनुसरण करता है)", isCorrect: true },
      { label: "B", text: "Only Conclusion II follows (केवल निष्कर्ष II अनुसरण करता है)", isCorrect: false },
      { label: "C", text: "Both Conclusions I and II follow (दोनों निष्कर्ष अनुसरण करते हैं)", isCorrect: false },
      { label: "D", text: "Neither follows (कोई भी अनुसरण नहीं करता)", isCorrect: false },
    ],
    sourceAnswer: "A",
    aiSuggestedAnswer: "A",
    explanation: "Since all books are pens, a subset of pens is definitely books (Conclusion I follows). There is no direct overlap established between pencils and books, so Conclusion II does not necessarily follow.",
    sourcePage: 2,
    confidence: { question: 0.97, options: 0.96, classification: 0.95, answer: 1.0 },
  },

  // SECTION 2: Quantitative Aptitude
  {
    questionNumber: 5,
    language: "en",
    subject: "Quantitative Aptitude",
    topic: "Percentage",
    subtopic: "Successive Changes",
    difficulty: "MEDIUM",
    questionText: "If the price of petrol increases by $20\\%$ and its consumption is decreased by $10\\%$, what is the percentage change in the net expenditure on petrol?",
    hasVisualContent: false,
    options: [
      { label: "A", text: "$8\\%$ increase", isCorrect: true },
      { label: "B", text: "$10\\%$ increase", isCorrect: false },
      { label: "C", text: "$8\\%$ decrease", isCorrect: false },
      { label: "D", text: "$12\\%$ increase", isCorrect: false },
    ],
    sourceAnswer: "A",
    aiSuggestedAnswer: "A",
    explanation: "Net change $= x + y + \\frac{xy}{100} = 20 - 10 + \\frac{20 \\times (-10)}{100} = 10 - 2 = +8\\%$ (an $8\\%$ increase).",
    sourcePage: 2,
    confidence: { question: 0.99, options: 0.98, classification: 0.98, answer: 1.0 },
  },
  {
    questionNumber: 6,
    language: "en",
    subject: "Quantitative Aptitude",
    topic: "Profit & Loss",
    subtopic: "Marked Price & Discount",
    difficulty: "MEDIUM",
    questionText: "A trader marks his goods $40\\%$ above the cost price and allows a discount of $25\\%$ on the marked price. Find his profit percentage.",
    hasVisualContent: false,
    options: [
      { label: "A", text: "$4\\%$", isCorrect: false },
      { label: "B", text: "$5\\%$", isCorrect: true },
      { label: "C", text: "$6\\%$", isCorrect: false },
      { label: "D", text: "$8\\%$", isCorrect: false },
    ],
    sourceAnswer: "B",
    aiSuggestedAnswer: "B",
    explanation: "Let Cost Price = 100. Marked Price = 140. Selling Price after $25\\%$ discount $= 140 \\times 0.75 = 105$. Profit $= 105 - 100 = 5\\%$.",
    sourcePage: 2,
    confidence: { question: 0.99, options: 0.98, classification: 0.99, answer: 1.0 },
  },
  {
    questionNumber: 7,
    language: "en",
    subject: "Quantitative Aptitude",
    topic: "Algebra",
    subtopic: "Algebraic Identities",
    difficulty: "HARD",
    questionText: "If $x + \\frac{1}{x} = 5$, find the value of $x^3 + \\frac{1}{x^3}$.",
    hasVisualContent: false,
    options: [
      { label: "A", text: "$110$", isCorrect: true },
      { label: "B", text: "$125$", isCorrect: false },
      { label: "C", text: "$140$", isCorrect: false },
      { label: "D", text: "$115$", isCorrect: false },
    ],
    sourceAnswer: "A",
    aiSuggestedAnswer: "A",
    explanation: "Using the identity $x^3 + \\frac{1}{x^3} = (x + \\frac{1}{x})^3 - 3(x + \\frac{1}{x}) = 5^3 - 3(5) = 125 - 15 = 110$.",
    sourcePage: 3,
    confidence: { question: 0.99, options: 0.99, classification: 0.99, answer: 1.0 },
  },
  {
    questionNumber: 8,
    language: "en",
    subject: "Quantitative Aptitude",
    topic: "Geometry",
    subtopic: "Circles & Tangents",
    difficulty: "HARD",
    questionText: "In the accompanying geometry diagram, $PT$ is a tangent to the circle at point $T$, and secant line $PAB$ passes through the center. If $PA = 8\\text{ cm}$ and $AB = 10\\text{ cm}$, determine the exact length of the tangent segment $PT$.",
    hasVisualContent: true,
    imageUrl: "/sample-diagram.svg",
    options: [
      { label: "A", text: "$10\\text{ cm}$", isCorrect: false },
      { label: "B", text: "$12\\text{ cm}$", isCorrect: true },
      { label: "C", text: "$14\\text{ cm}$", isCorrect: false },
      { label: "D", text: "$16\\text{ cm}$", isCorrect: false },
    ],
    sourceAnswer: "B",
    aiSuggestedAnswer: "B",
    explanation: "By the Tangent-Secant Theorem: $PT^2 = PA \\times PB$. Here $PB = PA + AB = 8 + 10 = 18\\text{ cm}$. Hence $PT^2 = 8 \\times 18 = 144 \\implies PT = \\sqrt{144} = 12\\text{ cm}$.",
    sourcePage: 3,
    confidence: { question: 0.97, options: 0.96, classification: 0.96, answer: 1.0 },
  },

  // SECTION 3: English Language
  {
    questionNumber: 9,
    language: "en",
    subject: "English Language",
    topic: "Spot the Error",
    subtopic: "Subject-Verb Agreement",
    difficulty: "MEDIUM",
    questionText: "Identify the segment that contains a grammatical error:\n\n'Neither the principal nor the lecturers was present at the academic council meeting.'",
    hasVisualContent: false,
    options: [
      { label: "A", text: "Neither the principal", isCorrect: false },
      { label: "B", text: "nor the lecturers was present", isCorrect: true },
      { label: "C", text: "at the academic", isCorrect: false },
      { label: "D", text: "council meeting", isCorrect: false },
    ],
    sourceAnswer: "B",
    aiSuggestedAnswer: "B",
    explanation: "When two subjects are joined by 'neither... nor', the verb must agree with the closest subject ('lecturers' is plural, so it requires 'were present' instead of 'was present').",
    sourcePage: 3,
    confidence: { question: 0.98, options: 0.97, classification: 0.97, answer: 1.0 },
  },
  {
    questionNumber: 10,
    language: "en",
    subject: "English Language",
    topic: "Synonyms & Antonyms",
    subtopic: "Vocabulary",
    difficulty: "MEDIUM",
    questionText: "Select the most appropriate SYNONYM of the given word:\n\nMETICULOUS",
    hasVisualContent: false,
    options: [
      { label: "A", text: "Careless", isCorrect: false },
      { label: "B", text: "Painstaking", isCorrect: true },
      { label: "C", text: "Hasty", isCorrect: false },
      { label: "D", text: "Superficial", isCorrect: false },
    ],
    sourceAnswer: "B",
    aiSuggestedAnswer: "B",
    explanation: "'Meticulous' means showing great attention to detail; very careful and precise. 'Painstaking' is an exact synonym.",
    sourcePage: 4,
    confidence: { question: 0.98, options: 0.98, classification: 0.98, answer: 1.0 },
  },
  {
    questionNumber: 11,
    language: "en",
    subject: "English Language",
    topic: "Idioms & Phrases",
    subtopic: "Figurative Language",
    difficulty: "EASY",
    questionText: "Select the correct meaning of the underlined idiom:\n\n'The new administrative officer decided to leave no stone unturned to uncover the financial discrepancies.'",
    hasVisualContent: false,
    options: [
      { label: "A", text: "To make every possible effort", isCorrect: true },
      { label: "B", text: "To give up halfway", isCorrect: false },
      { label: "C", text: "To act carelessly", isCorrect: false },
      { label: "D", text: "To cause physical damage", isCorrect: false },
    ],
    sourceAnswer: "A",
    aiSuggestedAnswer: "A",
    explanation: "The idiom 'leave no stone unturned' means to try every possible means to achieve something or find an answer.",
    sourcePage: 4,
    confidence: { question: 0.99, options: 0.98, classification: 0.98, answer: 1.0 },
  },

  // SECTION 4: General Awareness
  {
    questionNumber: 12,
    language: "bilingual",
    subject: "General Awareness",
    topic: "Indian Polity",
    subtopic: "Constitutional Amendments",
    difficulty: "MEDIUM",
    questionText: "By which Constitutional Amendment Act was the voting age in India reduced from 21 years to 18 years?\nकिस संविधान संशोधन अधिनियम द्वारा भारत में मतदान की आयु 21 वर्ष से घटाकर 18 वर्ष की गई थी?",
    hasVisualContent: false,
    options: [
      { label: "A", text: "42nd Amendment Act, 1976 (42वां संशोधन)", isCorrect: false },
      { label: "B", text: "44th Amendment Act, 1978 (44वां संशोधन)", isCorrect: false },
      { label: "C", text: "61st Amendment Act, 1988 (61वां संशोधन)", isCorrect: true },
      { label: "D", text: "73rd Amendment Act, 1992 (73वां संशोधन)", isCorrect: false },
    ],
    sourceAnswer: "C",
    aiSuggestedAnswer: "C",
    explanation: "The 61st Constitutional Amendment Act, 1988 (which came into force in 1989) amended Article 326 to reduce the voting age from 21 to 18.",
    sourcePage: 4,
    confidence: { question: 0.99, options: 0.99, classification: 0.99, answer: 1.0 },
  },
  {
    questionNumber: 13,
    language: "en",
    subject: "General Awareness",
    topic: "Modern History",
    subtopic: "Freedom Movement",
    difficulty: "EASY",
    questionText: "In which year did the historic Dandi March (Salt Satyagraha) led by Mahatma Gandhi commence from Sabarmati Ashram?",
    hasVisualContent: false,
    options: [
      { label: "A", text: "1928", isCorrect: false },
      { label: "B", text: "1930", isCorrect: true },
      { label: "C", text: "1932", isCorrect: false },
      { label: "D", text: "1942", isCorrect: false },
    ],
    sourceAnswer: "B",
    aiSuggestedAnswer: "B",
    explanation: "The Dandi March began on March 12, 1930, from Sabarmati Ashram in Ahmedabad and concluded at Dandi on April 6, 1930.",
    sourcePage: 5,
    confidence: { question: 0.99, options: 0.98, classification: 0.98, answer: 1.0 },
  },
  {
    questionNumber: 14,
    language: "en",
    subject: "General Awareness",
    topic: "General Science",
    subtopic: "Biology & Human Physiology",
    difficulty: "EASY",
    questionText: "Which of the following blood groups is known as the 'Universal Donor'?",
    hasVisualContent: false,
    options: [
      { label: "A", text: "O negative (O-)", isCorrect: true },
      { label: "B", text: "AB positive (AB+)", isCorrect: false },
      { label: "C", text: "A positive (A+)", isCorrect: false },
      { label: "D", text: "B negative (B-)", isCorrect: false },
    ],
    sourceAnswer: "A",
    aiSuggestedAnswer: "A",
    explanation: "O-negative blood lacks A, B, and Rh antigens, allowing it to be safely transfused to almost any recipient in emergency scenarios.",
    sourcePage: 5,
    confidence: { question: 0.99, options: 0.98, classification: 0.98, answer: 1.0 },
  },
  {
    questionNumber: 15,
    language: "bilingual",
    subject: "General Awareness",
    topic: "Geography",
    subtopic: "Indian Rivers",
    difficulty: "MEDIUM",
    questionText: "Which of the following peninsular rivers in India flows westward into the Arabian Sea through a rift valley?\nनिम्नलिखित में से कौन-सी प्रायद्वीपीय नदी एक भ्रंश घाटी से होकर पश्चिम की ओर अरब सागर में गिरती है?",
    hasVisualContent: false,
    options: [
      { label: "A", text: "Godavari (गोदावरी)", isCorrect: false },
      { label: "B", text: "Krishna (कृष्णा)", isCorrect: false },
      { label: "C", text: "Narmada (नर्मदा)", isCorrect: true },
      { label: "D", text: "Mahanadi (महानदी)", isCorrect: false },
    ],
    sourceAnswer: null, // Test case where source answer was missing, AI inferred C
    aiSuggestedAnswer: "C",
    explanation: "The Narmada and Tapti rivers flow westwards through rift valleys between the Vindhya and Satpura ranges and drain into the Arabian Sea.",
    sourcePage: 5,
    confidence: { question: 0.98, options: 0.97, classification: 0.97, answer: 0.88 },
  },
];
