version: '3.8'

services:
  examforge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: examforge-ai-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env
    volumes:
      - examforge-data:/app/prisma
      - examforge-uploads:/app/public/uploads

volumes:
  examforge-data:
  examforge-uploads:
